#!/bin/bash
### BEGIN INIT INFO
# Provides:			node-tcp-proxy
# Required-Start:	$local_fs $remote_fs
# Required-Stop:	$local_fs $remote_fs
# Should-Start:		$syslog
# Should-Stop:		$syslog
# Default-Start:	2 3 4 5
# Default-Stop:		0 1 6
# Short-Description: Start or stop the node-tcp-proxy daemon.
### END INIT INFO

# clear poisonned environment
unset TMPDIR

NAME=node-tcp-proxy
DAEMON=$(which forever)
BASE=/var/run/$NAME
PID=$BASE/$NAME.pid
USER=node
SCRIPT="/opt/node-tcp-proxy/custom-proxy.js"

test -x "$DAEMON" || exit 0

. /lib/lsb/init-functions

case "$1" in
	start)
		log_daemon_msg "Starting $NAME"
		start-stop-daemon --chuid $USER \
			--start --quiet \
			--pidfile $PID \
			--exec $DAEMON -- start --silent --pidfile $PID --minUptime 30000 $SCRIPT >/dev/null
	RETVAL=$?
		log_end_msg $RETVAL
		;;
	stop)
		log_daemon_msg "Stopping $NAME"
		$DAEMON stop --silent $SCRIPT >/dev/null
		RETVAL=$?
		log_end_msg $RETVAL
		;;
	restart)
		$0 stop
		$0 start
		;;
	status)
	status_of_proc -p "$PID" $DAEMON $NAME
	;;
	*)
		echo "Usage: /etc/init.d/xinetd {start|stop|restart|status}"
		exit 1
		;;
esac

exit $RETVAL
